# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: MW APP PHP

on:
  push:
    branches: [ "run_test" ]
  pull_request:
    branches: [ "run_test" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    #runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install MW
      run: |
        sudo bash scripts/install_dev.sh
    - name: Install PHP53
      run: |
        cd /www/server/mdserver-web/plugins/php && sudo bash install.sh install 53
    - name: Install PHP54
      run: |
        cd /www/server/mdserver-web/plugins/php && sudo bash install.sh install 54
    - name: Install PHP55
      run: |
        cd /www/server/mdserver-web/plugins/php && sudo bash install.sh install 55
    - name: Install PHP56
      run: |
        cd /www/server/mdserver-web/plugins/php && sudo bash install.sh install 56
    - name: Install PHP70
      run: |
        cd /www/server/mdserver-web/plugins/php && sudo bash install.sh install 70
    - name: Install PHP71
      run: |
        cd /www/server/mdserver-web/plugins/php && sudo bash install.sh install 71
    - name: Install PHP72
      run: |
        cd /www/server/mdserver-web/plugins/php && sudo bash install.sh install 72
    - name: Install PHP73
      run: |
        cd /www/server/mdserver-web/plugins/php && sudo bash install.sh install 73
    - name: Install PHP74
      run: |
        cd /www/server/mdserver-web/plugins/php && sudo bash install.sh install 74
    - name: Install PHP80
      run: |
        cd /www/server/mdserver-web/plugins/php && sudo bash install.sh install 80
    - name: Install PHP81
      run: |
        cd /www/server/mdserver-web/plugins/php && sudo bash install.sh install 81
    - name: Start DEBUG
      run: |
        source /www/server/mdserver-web/bin/activate && cd web && gunicorn -c setting.py app:app
        cd /www/server/mdserver-web && python3 panel_task.py &
