# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: MW APP MySQL57

on:
  push:
    branches: [ "run_test" ]
  pull_request:
    branches: [ "run_test" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    #runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install MW
      run: |
        sudo bash scripts/install_dev.sh
    - name: Install MySQL57
      run: |
        cd /www/server/mdserver-web/plugins/mysql && sudo bash install.sh install 5.7
    - name: Start DEBUG
      run: |
        cd web && gunicorn -c setting.py app:app
        python3 panel_task.py &
